CREATE TABLE `ARTIST` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(255),
	`description` VARCHAR(255),
	PRIMARY KEY(`id`)
);


CREATE TABLE `STYLE` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`description` VARCHAR(255),
	`name` VARCHAR(255),
	PRIMARY KEY(`id`)
);


CREATE TABLE `EVENT` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(255),
	`date&time` DATETIME,
	`venue` VARCHAR(255),
	`description` VARCHAR(255),
	PRIMARY KEY(`id`)
);


CREATE TABLE `city` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`venue` VARCHAR(255),
	`date&time` DATETIME,
	PRIMARY KEY(`id`)
);


CREATE TABLE `ARTISTSTYLE` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	PRIMARY KEY(`id`)
);


CREATE TABLE `ARTISTEVENT` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	PRIMARY KEY(`id`)
);


CREATE TABLE `user` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(255),
	`pass` ,
	PRIMARY KEY(`id`)
) COMMENT='user should b enum: ';


CREATE TABLE `forum` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	PRIMARY KEY(`id`)
);


ALTER TABLE `STYLE`
ADD FOREIGN KEY(`id`) REFERENCES `ARTISTSTYLE`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ARTIST`
ADD FOREIGN KEY(`id`) REFERENCES `ARTISTSTYLE`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ARTIST`
ADD FOREIGN KEY(`id`) REFERENCES `ARTISTEVENT`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `EVENT`
ADD FOREIGN KEY(`id`) REFERENCES `ARTISTEVENT`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `city`
ADD FOREIGN KEY(`venue`) REFERENCES `EVENT`(`venue`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `city`
ADD FOREIGN KEY(`date&time`) REFERENCES `EVENT`(`date&time`)
ON UPDATE NO ACTION ON DELETE NO ACTION;