CREATE TABLE `ARTIST` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(255),
	`description` VARCHAR(255),
	PRIMARY KEY(`id`)
);


CREATE TABLE `STYLE` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	
	`name` VARCHAR(255),
	PRIMARY KEY(`id`)
);


CREATE TABLE `EVENT` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(255),
	`date_time` DATETIME,
	`venue_id` INTEGER NOT NULL,
	PRIMARY KEY(`id`),
	FOREIGN KEY(`venue_id`) REFERENCES `VENUE`(`id`)
);


CREATE TABLE `CITY` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(255),
	PRIMARY KEY(`id`)
);

CREATE TABLE `VENUE` (
    `id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
    `name` VARCHAR(255),
    `city_id` INTEGER NOT NULL, 
    PRIMARY KEY(`id`),
    FOREIGN KEY(`city_id`) REFERENCES `CITY`(`id`) 
);


CREATE TABLE `ARTISTSTYLE` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	PRIMARY KEY(`id`)
);


CREATE TABLE `ARTISTEVENT` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	PRIMARY KEY(`id`)
);


CREATE TABLE USER (
    id INT NOT NULL AUTO_INCREMENT UNIQUE,
    name VARCHAR(255),
    pass CHAR(60), 
    role ENUM('admin', 'user') NOT NULL DEFAULT 'user', 
	PRIMARY KEY(`id`)
)


CREATE TABLE `FORUM` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	PRIMARY KEY(`id`)
);


ALTER TABLE `STYLE`
ADD FOREIGN KEY(`id`) REFERENCES `ARTISTSTYLE`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ARTIST`
ADD FOREIGN KEY(`id`) REFERENCES `ARTISTSTYLE`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ARTIST`
ADD FOREIGN KEY(`id`) REFERENCES `ARTISTEVENT`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `EVENT`
ADD FOREIGN KEY(`id`) REFERENCES `ARTISTEVENT`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `EVENT`
ADD FOREIGN KEY(`venue_id`) REFERENCES `VENUE`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CITY`
ADD FOREIGN KEY(`VENUE`) REFERENCES `EVENT`(`VENUE`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CITY`
ADD FOREIGN KEY(`id`) REFERENCES `VENUE`(`city_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;